# Generated by Django 4.1.5 on 2023-01-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='karbar',
        ),
    ]
