# Generated by Django 4.1.4 on 2023-01-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='karbar',
        ),
    ]
