# Generated by Django 4.1.4 on 2023-01-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karbar',
            name='password',
            field=models.IntegerField(max_length=150),
        ),
    ]
