# Generated by Django 4.1.4 on 2023-01-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_alter_karbar_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karbar',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
