# Generated by Django 4.1.4 on 2023-01-19 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_alter_karbar_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='karbar',
        ),
    ]
