# Generated by Django 4.1.4 on 2023-01-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='karbar',
        ),
    ]
