# Generated by Django 4.1.4 on 2023-01-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('cmt', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
