# Generated by Django 4.1.4 on 2023-01-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
