# Generated by Django 4.1.4 on 2023-01-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='karbar',
            name='profile',
            field=models.ImageField(default='pictures/default.png', upload_to='pictures/'),
        ),
    ]
