# Generated by Django 4.1.4 on 2023-01-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_karbar_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='karbar',
        ),
    ]
