# Generated by Django 4.1.4 on 2023-01-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0017_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='homeworks',
            new_name='file',
        ),
    ]
