# Generated by Django 4.1.4 on 2023-01-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0018_rename_homeworks_homework_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karbar',
            name='homeworks',
        ),
    ]
