# Generated by Django 4.2 on 2023-04-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0019_remove_karbar_homeworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='cm',
            field=models.CharField(max_length=1500),
        ),
    ]
